{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "androidxSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "androidx-multiplatform-docs"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-1.2.1-multiplatform-sources.jar",
          "url": "material3-window-size-class-1.2.1-multiplatform-sources.jar",
          "size": 8812,
          "sha512": "57d7309afe2675959e541130d072a41c8677ceccc1a0da714fffa5e3454015cb58ce42b6820bba614d9a259783787398446e6ca5b39003d8ed97b07eaafbc96f",
          "sha256": "d1f1ad58e8301da3f26e3e9463982bf119f441a33bbb00d9c16958d1ea2de8ff",
          "sha1": "00de116a0efe83906154a6846949def0f6b999e7",
          "md5": "48b00ecf2012f332ed31f69719b1c89c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "apiLevels.json",
          "url": "material3-window-size-class-1.2.1-versionMetadata.json",
          "size": 2247,
          "sha512": "d861e4ce677824b632f505747c480cdfbf345c118e868022ce94fef98b86b01e91bf992afbcce005dd8eb1781a600606fa4a3bb04a856a0d20d06a7828c576d7",
          "sha256": "723d813ee6415632f4a5a74833ff8d5264c7ce789d876f7226c44fb0208514ea",
          "sha1": "2c0e134a7285551b5aac6b876e5fa997cb78b27c",
          "md5": "a8f9d392e76a457fa012bf2b9f3ca78f"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-metadata-1.2.1.jar",
          "url": "material3-window-size-class-1.2.1.jar",
          "size": 738,
          "sha512": "7549f44a320ce7b216c7b7d516ac508e695eea02e6f8da256800a9fc81d958345d7b87e55e0a7085f330d70c77fd599610c50c39fe58ff6501f9b9c7910812d5",
          "sha256": "2507c1050a4ad2ea69d634c76c8f62e2674d62b3f9a7ed966790147ef3873d11",
          "sha1": "dd0d71e8e11819578c1cc5de45ab17f028cf056a",
          "md5": "2c68f6f1428d390712a367ece651f61e"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.2.1"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-kotlin-1.2.1-sources.jar",
          "url": "material3-window-size-class-1.2.1-sources.jar",
          "size": 6556,
          "sha512": "b645ff0e831c2459402669193d9bb7f010b3051b75dd0239d242c9f1ad29b1e9adde5a3651f817d7d23b52766b1999b4188f6e1f89e43f89a954697f739703f4",
          "sha256": "5cb535d58dc4b5b33e45ae23296258e848124f6cc77b9ff8b59340494a08951a",
          "sha1": "07f1acfb702452a534207106887550ca6c36f9d1",
          "md5": "5b0bd640016f7ce7782c1d8dca68d369"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-android/1.2.1/material3-window-size-class-android-1.2.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-android",
        "version": "1.2.1"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-android/1.2.1/material3-window-size-class-android-1.2.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-android",
        "version": "1.2.1"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-android/1.2.1/material3-window-size-class-android-1.2.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-android",
        "version": "1.2.1"
      }
    },
    {
      "name": "desktopApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/1.2.1/material3-window-size-class-desktop-1.2.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "1.2.1"
      }
    },
    {
      "name": "desktopRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/1.2.1/material3-window-size-class-desktop-1.2.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "1.2.1"
      }
    },
    {
      "name": "desktopSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../material3-window-size-class-desktop/1.2.1/material3-window-size-class-desktop-1.2.1.module",
        "group": "androidx.compose.material3",
        "module": "material3-window-size-class-desktop",
        "version": "1.2.1"
      }
    }
  ]
}